#' Histórico de proyectos adjudicados ANID
#'
#' Acceso a los datos y herramientas accesorias para la exploración y visualización
#' de la información de adjudicación de proyectos históricos de la Agencia Nacional
#' de Investigación y Desarrollo (ANID), Chile.
#'
#' @format Un data frame con 38,744 filas y 22 variables:
#'
#'   - \code{codigo_proyecto}:...
#'   - \code{n}:...
#'   - \code{subdireccion}:...
#'   - \code{programa}:...
#'   - \code{instrumento}:...
#'   - \code{nombre_concurso}:...
#'   - \code{ano_curso}:...
#'   - \code{ano_fallo}:...
#'   - \code{nombre_proyecto}:...
#'   - \code{area_ocde}:...
#'   - \code{disciplina}:...
#'   - \code{grupo_evaluacion}:...
#'   - \code{duracion_meses}:...
#'   - \code{tipo_beneficiario}:...
#'   - \code{nombre_responsable}:...
#'   - \code{sexo}:...
#'   - \code{institucion_principal}:...
#'   - \code{macrozona}:...
#'   - \code{region_ejecucion}:...
#'   - \code{monto_adjudicado_miles}:...
#'   - \code{nota_monto}:...
#'   - \code{ano_finalizacion}:...
#'
#' @source Los datos fueron recopilados del repositorio público ANID en
#' [GitHub](https://github.com/ANID-GITHUB/Historico-de-Proyectos-Adjudicados).
"proyectosanid"
