#' Histórico de proyectos adjudicados ANID
#'
#' Datos históricos de los proyectos adjudicados bajo ANID.
#'
#' @format Un data frame con 37,194 filas y 23 variables:
#'
#'   - \code{region_ejecución}: ...
#'   - \code{institucion_principal}: ...
#'   - \code{codigo_proyecto}: ...
#'   - \code{n}: ...
#'   - \code{subdireccion}: ...
#'   - \code{programa}: ...
#'   - \code{instrumento}: ...
#'   - \code{nombre_concurso}: ...
#'   - \code{ano_curso}: ...
#'   - \code{ano_fallo}: ...
#'   - \code{nombre_proyecto}: ...
#'   - \code{area_ocde}: ...
#'   - \code{disciplina}: ...
#'   - \code{grupo_evaluacion}: ...
#'   - \code{duracion_meses}: ...
#'   - \code{tipo_beneficiario}: ...
#'   - \code{nombre_responsable}: ...
#'   - \code{sexo}: ...
#'   - \code{macrozona}: ...
#'   - \code{monto_adjudicado_miles}: ...
#'   - \code{sinfo_nosolicita}: ...
#'   - \code{ano_finalizacion}: ...
#'   - \code{ubicacion_institucion}: ...
#'
#' @source Los datos fueron recopilados del repositorio público ANID-GITHUB/Historico-de-Proyectos-Adjudicados
#' usando el archivo 'BDH_Proyectos.csv'.
"proyectosanid"
